// TODO: Replace this stub with the real file generated by flutterfire CLI:
//   flutter pub global activate flutterfire_cli
//   flutterfire configure --project=tow-factory
//
// Until then, Firebase push notifications will not work, but socket-based
// in-app notifications will function normally.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace ALL values below by running: flutterfire configure --project=tow-factory
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'tow-factory',
    storageBucket: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOWxG6ywIkNFU351of8s-t_B46kR_3f88',
    appId: '1:757718542396:android:5587c141e48df103667b39',
    messagingSenderId: '757718542396',
    projectId: 'tow-factory',
    storageBucket: 'tow-factory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmCY3NJxMxZVjK946q8wR11QCCNZLQUc',
    appId: '1:757718542396:ios:d65054053046c13c667b39',
    messagingSenderId: '757718542396',
    projectId: 'tow-factory',
    storageBucket: 'tow-factory.firebasestorage.app',
    iosBundleId: 'com.example.tfDriverApp',
  );

}